services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql
    ports:
      - '3307:3306'
    volumes:
      - e:/tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: aaa
      MYSQL_ROOT_PASSWORD: root
  redis-container:
    image: redis
    ports:
      - '6380:6379'
    volumes:
      - e:/tmp/redis2:/data
