version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - e:/tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: aaa
      MYSQL_ROOT_PASSWORD: root
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - e:/tmp/redis2:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
